name: Testing context, properties and variables

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  global_var: This is global variable

jobs:
  exploring_contexts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: printing github info
        run: |
             echo '${{toJson(github)}}'
             echo '${{toJson(runner)}}'
      - name: printing github repo name 
        run: echo ${{github.repository}}
      - name: printing github repo actor
        run: echo ${{github.actor}}
  
  exploring_variables:
    runs-on: ubuntu-latest
    env: 
      exploring_variables_var: This var belongs to exploring variables job
    steps:
      - name: just printing local varaible
        run: echo ${{env.exploring_variables_var}}
      - name: printing global variable
        run: echo ${{env.global_var}}





