name: Trying contexts and variables

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  global_env_var: Global level env variable

jobs:
  context_exploration:
    runs-on: ubuntu-latest
    env:
      job_env_var: Job level env variable, will be used while printing
    steps:
      - name: checkout code onto the runner
        uses: actions/checkout@v5
      - name: printing repository context
        run: echo ${{github.repository}}
      - name: printing github actor context
        run: echo ${{github.actor}}
      - name: Printing job env var
        run: echo ${{env.job_env_var}}
    
  installing_and_compiling_maven:
      runs-on: ubuntu-latest
      steps:
        - name: actual repo checkout
          uses: actions/checkout@v5
        - name: Cleaning target package
          run: mvn clean
        - name: compiling the code
          run: mvn compile

  exploring_variables:
      runs-on: ubuntu-latest
      steps:
        - name: printing global variable
          run: echo ${{env.global_env_var}}
        - name: printing vars goal variable
          run: echo ${{vars.GOAL}}
        